"""product_user

Revision ID: 79420535e10d
Revises: b7acc716339a
Create Date: 2021-08-31 13:50:49.317129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79420535e10d'
down_revision = 'b7acc716339a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_user', sa.Column('count_product', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_user', 'count_product')
    # ### end Alembic commands ###
