"""product_user

Revision ID: b7acc716339a
Revises: e54dd88b57cc
Create Date: 2021-08-31 13:11:34.110495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7acc716339a'
down_revision = 'e54dd88b57cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'vendor_code')
    op.add_column('product_user', sa.Column('vendor_code', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_user', 'vendor_code')
    op.add_column('product', sa.Column('vendor_code', mysql.VARCHAR(collation='utf8_unicode_ci', length=12), nullable=True))
    # ### end Alembic commands ###
