"""price

Revision ID: dc2a52930cb1
Revises: ddfa36e54f03
Create Date: 2021-08-31 21:08:42.755201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc2a52930cb1'
down_revision = 'ddfa36e54f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('amount', sa.Float(), nullable=True))
    op.drop_column('price', 'cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('cost', mysql.FLOAT(), nullable=True))
    op.drop_column('price', 'amount')
    # ### end Alembic commands ###
